# Generated by Django 6.0 on 2025-12-31 06:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(255)])),
                ('license_number', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)])),
                ('home_terminal', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(255)])),
                ('main_office_address', models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license_number'], name='drivers_license_29348f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('duty_statuses', models.JSONField(help_text='Array of duty status objects')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shipping_documents', models.CharField(blank=True, max_length=255, null=True)),
                ('co_driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('total_miles', models.IntegerField(default=0)),
                ('total_miles_today', models.IntegerField(default=0)),
                ('total_miles_yesterday', models.IntegerField(default=0)),
                ('hours_off_duty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hours_sleeper', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hours_driving', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hours_on_duty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hours_total', models.DecimalField(decimal_places=2, default=24.0, max_digits=5)),
                ('is_compliant', models.BooleanField(blank=True, null=True)),
                ('violations', models.JSONField(blank=True, default=list, help_text='Array of violation objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='logs.driver')),
            ],
            options={
                'db_table': 'daily_logs',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['driver'], name='daily_logs_driver__b8f9bf_idx'), models.Index(fields=['date'], name='daily_logs_date_f73777_idx'), models.Index(fields=['driver', 'date'], name='daily_logs_driver__a6cc54_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver', 'date'), name='unique_driver_date')],
            },
        ),
    ]
