# Generated by Django 6.0 on 2025-12-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_add_gps_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='locationcache',
            new_name='location_ca_locatio_c95bb8_idx',
            old_name='logs_locati_locatio_idx',
        ),
    ]
